export const DATA = [
  {
    athlete: 'Michael Phelps',
    age: 19,
    country: 'United States',
    year: 2008,
    date: '2021-03-09T12:15:06.692Z',
    sport: 'Swimming',
    gold: 8,
    silver: 0,
    bronze: 0,
    total: 8,
    status: 'error',
    updated: '2020-11-05T14:36:22.000Z',
    abbrevation: 'MP',
    id: 1,
    switch: false,
    chkbox: false,
    colorpick: '#BF6397',
    hasComments: true,
  },
  {
    athlete: 'Michael Phelps',
    age: 19,
    country: 'United States',
    year: 2004,
    date: '2021-03-09T12:15:06.692Z',
    sport: 'Swimming',
    gold: 6,
    silver: 0,
    bronze: 2,
    total: 8,
    status: 'inProgress',
    updated: '2020-11-06T14:36:22.000Z',
    abbrevation: 'MS',
    id: 2,
    commentsCount: 2,
    switch: false,
    chkbox: false,
    colorpick: '#BF6397',
  },
  {
    athlete: 'Michael Phelps',
    age: 27,
    country: 'United States',
    year: 2012,
    date: '2021-03-09T12:15:06.692Z',
    sport: 'Swimming',
    gold: 4,
    silver: 2,
    bronze: 0,
    total: 6,
    status: 'inProcess',
    updated: '2020-11-07T14:36:22.000Z',
    abbrevation: 'MR',
    id: 3,
    commentsCount: 3,
    switch: false,
    chkbox: false,
    colorpick: '#BF6397',
  },
  {
    athlete: 'Natalie Coughlin',
    age: 25,
    country: 'United States',
    year: 2008,
    date: '2021-03-09T12:15:06.692Z',
    sport: 'Swimming',
    gold: 1,
    silver: 2,
    bronze: 3,
    total: 6,
    status: 'critical',
    updated: '2020-11-04T14:36:22.000Z',
    created: '2020-11-04T14:36:22.000Z',
    abbrevation: 'NC',
    switch: false,
    chkbox: false,
    colorpick: '#BF6397',
  },
  {
    athlete: 'Aleksey Nemov',
    age: 24,
    country: 'Russia',
    year: 2000,
    date: '01/10/2000',
    sport: 'Gymnastics',
    gold: 2,
    silver: 1,
    bronze: 3,
    total: 6,
    status: 'warning',
    updated: '2020-09-01T14:36:22.000Z',
    abbrevation: 'NC',
    switch: false,
    chkbox: false,
    colorpick: '#BF6397',
  },
  {
    athlete: 'Alicia Coutts',
    age: 24,
    country: 'Australia',
    year: 2012,
    date: '2021-03-09T12:15:06.692Z',
    sport: 'Swimming',
    gold: 1,
    silver: 3,
    bronze: 1,
    total: 6,
    status: 'warning',
    updated: '2020-02-28T14:36:22.000Z',
    abbrevation: 'NC',
    switch: false,
    chkbox: false,
    colorpick: '#BF6397',
  },
  {
    athlete: 'Missy Franklin',
    age: 17,
    country: 'United States',
    year: 2012,
    date: '2021-03-09T12:15:06.692Z',
    sport: 'Swimming',
    gold: 4,
    silver: 0,
    bronze: 1,
    total: 6,
    status: 'critical',
    updated: '2020-11-12T14:36:22.000Z',
    abbrevation: 'NC',
    switch: false,
    chkbox: false,
    colorpick: '#BF6397',
  },
  {
    athlete: 'Ryan Lochte',
    age: 27,
    country: 'United States',
    year: 2012,
    date: '2021-03-09T12:15:06.692Z',
    sport: 'Swimming',
    gold: 2,
    silver: 2,
    bronze: 1,
    total: 6,
    status: 'critical',
    updated: '2018-10-10T14:36:22.000Z',
    abbrevation: 'NC',
    switch: false,
    chkbox: false,
    colorpick: '#BF6397',
  },
  {
    athlete: 'Allison Schmitt',
    age: 22,
    country: 'United States',
    year: 2012,
    date: '2021-03-09T12:15:06.692Z',
    sport: 'Swimming',
    gold: 3,
    silver: 1,
    bronze: 1,
    total: 6,
    status: 'critical',
    updated: '2020-11-04T14:36:22.000Z',
    abbrevation: 'NC',
    switch: false,
    chkbox: false,
    colorpick: '#BF6397',
  },
  {
    athlete: 'Natalie Coughlin',
    age: 21,
    country: 'United States',
    year: 2004,
    date: '29/08/2004',
    sport: 'Swimming',
    gold: 2,
    silver: 2,
    bronze: 1,
    total: 6,
    status: 'warning',
    updated: '2020-11-04T14:36:22.000Z',
    abbrevation: 'NC',
    switch: false,
    chkbox: false,
    colorpick: '#BF6397',
  },
  {
    athlete: 'Ian Thorpe',
    age: 17,
    country: 'Australia',
    year: 2000,
    date: '01/10/2000',
    sport: 'Swimming',
    gold: 3,
    silver: 2,
    bronze: 0,
    total: 6,
    status: 'major',
    updated: '2020-11-04T14:36:22.000Z',
    abbrevation: 'NC',
    switch: false,
    chkbox: false,
    colorpick: '#BF6397',
  },
  {
    athlete: 'Dara Torres',
    age: 33,
    country: 'United States',
    year: 2000,
    date: '01/10/2000',
    sport: 'Swimming',
    gold: 2,
    silver: 0,
    bronze: 3,
    total: 6,
    status: 'warning',
    updated: '2020-11-04T14:36:22.000Z',
    abbrevation: 'NC',
    switch: false,
    chkbox: false,
    colorpick: '#BF6397',
  },
  {
    athlete: 'Cindy Klassen',
    age: 26,
    country: 'Canada',
    year: 2006,
    date: '26/02/2006',
    sport: 'Speed Skating',
    gold: 1,
    silver: 2,
    bronze: 2,
    total: 6,
    status: 'warning',
    updated: '2020-11-04T14:36:22.000Z',
    abbrevation: 'NC',
    switch: false,
    chkbox: false,
    colorpick: '#BF6397',
  },
  {
    athlete: 'Nastia Liukin',
    age: 18,
    country: 'United States',
    year: 2008,
    date: '2021-03-09T12:15:06.692Z',
    sport: 'Gymnastics',
    gold: 1,
    silver: 3,
    bronze: 1,
    total: 6,
    status: 'major',
    updated: '2020-11-04T14:36:22.000Z',
    abbrevation: 'NC',
    switch: false,
    chkbox: false,
    colorpick: '#BF6397',
  },
  {
    athlete: 'Marit Bjørgen',
    age: 29,
    country: 'Norway',
    year: 2010,
    date: '28/02/2010',
    sport: 'Cross Country Skiing',
    gold: 3,
    silver: 1,
    bronze: 1,
    total: 6,
    status: 'critical',
    updated: '2020-11-04T14:36:22.000Z',
    abbrevation: 'NC',
    switch: false,
    chkbox: false,
    colorpick: '#BF6397',
  },
  {
    athlete: 'Sun Yang',
    age: 20,
    country: 'China',
    year: 2012,
    date: '2021-03-09T12:15:06.692Z',
    sport: 'Swimming',
    gold: 2,
    silver: 1,
    bronze: 1,
    total: 6,
    status: 'critical',
    updated: '2020-11-04T14:36:22.000Z',
    abbrevation: 'NC',
    switch: false,
    chkbox: false,
    colorpick: '#BF6397',
  },
  {
    athlete: 'Kirsty Coventry',
    age: 24,
    country: 'Zimbabwe',
    year: 2008,
    date: '2021-03-09T12:15:06.692Z',
    sport: 'Swimming',
    gold: 1,
    silver: 3,
    bronze: 0,
    total: 6,
    status: 'critical',
    updated: '2020-11-04T14:36:22.000Z',
    abbrevation: 'NC',
    switch: false,
    chkbox: false,
    colorpick: '#BF6397',
  },
  {
    athlete: 'Libby Lenton-Trickett',
    age: 23,
    country: 'Australia',
    year: 2008,
    date: '2021-03-09T12:15:06.692Z',
    sport: 'Swimming',
    gold: 2,
    silver: 1,
    bronze: 1,
    total: 6,
    status: 'major',
    updated: '2020-11-04T14:36:22.000Z',
    abbrevation: 'NC',
    switch: false,
    chkbox: false,
    colorpick: '#BF6397',
  },
  {
    athlete: 'Ryan Lochte',
    age: 24,
    country: 'United States',
    year: 2008,
    date: '2021-03-09T12:15:06.692Z',
    sport: 'Swimming',
    gold: 2,
    silver: 0,
    bronze: 2,
    total: 6,
    status: 'major',
    updated: '2020-11-04T14:36:22.000Z',
    abbrevation: 'NC',
    switch: false,
    chkbox: false,
    colorpick: '#BF6397',
  },
  {
    athlete: 'Inge de Bruijn',
    age: 30,
    country: 'Netherlands',
    year: 2004,
    date: '29/08/2004',
    sport: 'Swimming',
    gold: 1,
    silver: 1,
    bronze: 2,
    total: 6,
    status: 'critical',
    updated: '2020-11-04T14:36:22.000Z',
    abbrevation: 'NC',
    switch: false,
    chkbox: false,
    colorpick: '#BF6397',
  },
  {
    athlete: 'Petria Thomas',
    age: 28,
    country: 'Australia',
    year: 2004,
    date: '29/08/2004',
    sport: 'Swimming',
    gold: 3,
    silver: 1,
    bronze: 0,
    total: 6,
    status: 'critical',
    updated: '2020-11-04T14:36:22.000Z',
    abbrevation: 'NC',
    switch: false,
    chkbox: false,
    colorpick: '#BF6397',
  },
  {
    athlete: 'Ian Thorpe',
    age: 21,
    country: 'Australia',
    year: 2004,
    date: '29/08/2004',
    sport: 'Swimming',
    gold: 2,
    silver: 1,
    bronze: 1,
    total: 6,
    status: 'major',
    updated: '2020-11-04T14:36:22.000Z',
    abbrevation: 'NC',
    switch: false,
    chkbox: false,
    colorpick: '#BF6397',
  },
  {
    athlete: 'Inge de Bruijn',
    age: 27,
    country: 'Netherlands',
    year: 2000,
    date: '01/10/2000',
    sport: 'Swimming',
    gold: 3,
    silver: 1,
    bronze: 0,
    total: 6,
    status: 'critical',
    updated: '2020-11-04T14:36:22.000Z',
    abbrevation: 'NC',
    switch: false,
    chkbox: false,
    colorpick: '#BF6397',
  },
  {
    athlete: 'Gary Hall Jr.',
    age: 25,
    country: 'United States',
    year: 2000,
    date: '01/10/2000',
    sport: 'Swimming',
    gold: 2,
    silver: 1,
    bronze: 1,
    total: 6,
    status: 'critical',
    updated: '2020-11-04T14:36:22.000Z',
    abbrevation: 'NC',
    switch: false,
    chkbox: false,
    colorpick: '#BF6397',
  },
  {
    athlete: 'Michael Klim',
    age: 23,
    country: 'Australia',
    year: 2000,
    date: '01/10/2000',
    sport: 'Swimming',
    gold: 2,
    silver: 2,
    bronze: 0,
    total: 6,
    status: 'critical',
    updated: '2020-11-04T14:36:22.000Z',
    abbrevation: 'NC',
    switch: false,
    chkbox: false,
    colorpick: '#BF6397',
  },
  {
    athlete: "Susie O'Neill",
    age: 27,
    country: 'Australia',
    year: 2000,
    date: '01/10/2000',
    sport: 'Swimming',
    gold: 1,
    silver: 3,
    bronze: 0,
    total: 6,
    status: 'critical',
    updated: '2020-11-04T14:36:22.000Z',
    abbrevation: 'NC',
    switch: false,
    chkbox: false,
    colorpick: '#BF6397',
  },
  {
    athlete: 'Jenny Thompson',
    age: 27,
    country: 'United States',
    year: 2000,
    date: '01/10/2000',
    sport: 'Swimming',
    gold: 3,
    silver: 0,
    bronze: 1,
    total: 6,
    status: 'critical',
    updated: '2020-11-04T14:36:22.000Z',
    abbrevation: 'NC',
    switch: false,
    chkbox: false,
    colorpick: '#BF6397',
  },
  {
    athlete: 'Pieter van den Hoogenband',
    age: 22,
    country: 'Netherlands',
    year: 2000,
    date: '01/10/2000',
    sport: 'Swimming',
    gold: 2,
    silver: 0,
    bronze: 2,
    total: 6,
    status: 'critical',
    updated: '2020-11-04T14:36:22.000Z',
    abbrevation: 'NC',
    switch: false,
    chkbox: false,
    colorpick: '#BF6397',
  },
  {
    athlete: 'An Hyeon-Su',
    age: 20,
    country: 'South Korea',
    year: 2006,
    date: '26/02/2006',
    sport: 'Short-Track Speed Skating',
    gold: 3,
    silver: 0,
    bronze: 1,
    total: 6,
    status: 'major',
    updated: '2020-11-04T14:36:22.000Z',
    abbrevation: 'NC',
    switch: false,
    chkbox: false,
    colorpick: '#BF6397',
  },
  {
    athlete: 'Aliya Mustafina',
    age: 17,
    country: 'Russia',
    year: 2012,
    date: '2021-03-09T12:15:06.692Z',
    sport: 'Gymnastics',
    gold: 1,
    silver: 1,
    bronze: 2,
    total: 6,
    status: 'major',
    updated: '2020-11-04T14:36:22.000Z',
    abbrevation: 'NC',
    switch: false,
    chkbox: false,
    colorpick: '#BF6397',
  },
  {
    athlete: 'Shawn Johnson',
    age: 16,
    country: 'United States',
    year: 2008,
    date: '2021-03-09T12:15:06.692Z',
    sport: 'Gymnastics',
    gold: 1,
    silver: 3,
    bronze: 0,
    total: 6,
    status: 'major',
    updated: '2020-11-04T14:36:22.000Z',
    abbrevation: 'NC',
    switch: false,
    chkbox: false,
    colorpick: '#BF6397',
  },
  {
    athlete: 'Dmitry Sautin',
    age: 26,
    country: 'Russia',
    year: 2000,
    date: '01/10/2000',
    sport: 'Diving',
    gold: 1,
    silver: 1,
    bronze: 2,
    total: 6,
    status: 'major',
    updated: '2020-11-04T14:36:22.000Z',
    abbrevation: 'NC',
    switch: false,
    chkbox: false,
    colorpick: '#BF6397',
  },
  {
    athlete: 'Leontien Zijlaard-van Moorsel',
    age: 30,
    country: 'Netherlands',
    year: 2000,
    date: '01/10/2000',
    sport: 'Cycling',
    gold: 3,
    silver: 1,
    bronze: 0,
    total: 6,
    status: 'major',
    updated: '2020-11-04T14:36:22.000Z',
    abbrevation: 'NC',
    switch: false,
    chkbox: false,
    colorpick: '#BF6397',
  },
  {
    athlete: 'Petter Northug Jr.',
    age: 24,
    country: 'Norway',
    year: 2010,
    date: '28/02/2010',
    sport: 'Cross Country Skiing',
    gold: 2,
    silver: 1,
    bronze: 1,
    total: 6,
    status: 'major',
    updated: '2020-11-04T14:36:22.000Z',
    abbrevation: 'NC',
    switch: false,
    chkbox: false,
    colorpick: '#BF6397',
  },
  {
    athlete: 'Ole Einar Bjørndalen',
    age: 28,
    country: 'Norway',
    year: 2002,
    date: '24/02/2002',
    sport: 'Biathlon',
    gold: 4,
    silver: 0,
    bronze: 0,
    total: 6,
    status: 'warning',
    updated: '2020-11-04T14:36:22.000Z',
    abbrevation: 'NC',
    switch: false,
    chkbox: false,
    colorpick: '#BF6397',
  },
  {
    athlete: 'Janica Kostelic',
    age: 20,
    country: 'Croatia',
    year: 2002,
    date: '24/02/2002',
    sport: 'Alpine Skiing',
    gold: 3,
    silver: 1,
    bronze: 0,
    total: 6,
    status: 'warning',
    updated: '2020-11-04T14:36:22.000Z',
    abbrevation: 'NC',
    switch: false,
    chkbox: false,
    colorpick: '#BF6397',
  },
  {
    athlete: 'Nathan Adrian',
    age: 23,
    country: 'United States',
    year: 2012,
    date: '2021-03-09T12:15:06.692Z',
    sport: 'Swimming',
    gold: 2,
    silver: 1,
    bronze: 0,
    total: 6,
    status: 'warning',
    updated: '2020-11-04T14:36:22.000Z',
    abbrevation: 'NC',
    switch: false,
    chkbox: false,
    colorpick: '#BF6397',
  },
  {
    athlete: 'Yannick Agnel',
    age: 20,
    country: 'France',
    year: 2012,
    date: '2021-03-09T12:15:06.692Z',
    sport: 'Swimming',
    gold: 2,
    silver: 1,
    bronze: 0,
    total: 6,
    status: 'warning',
    updated: '2020-11-04T14:36:22.000Z',
    abbrevation: 'NC',
    switch: false,
    chkbox: false,
    colorpick: '#BF6397',
  },
  {
    athlete: 'Brittany Elmslie',
    age: 18,
    country: 'Australia',
    year: 2012,
    date: '2021-03-09T12:15:06.692Z',
    sport: 'Swimming',
    gold: 1,
    silver: 2,
    bronze: 0,
    total: 6,
    status: 'warning',
    updated: '2020-11-04T14:36:22.000Z',
    abbrevation: 'NC',
    switch: false,
    chkbox: false,
    colorpick: '#BF6397',
  },
  {
    athlete: 'Matt Grevers',
    age: 27,
    country: 'United States',
    year: 2012,
    date: '2021-03-09T12:15:06.692Z',
    sport: 'Swimming',
    gold: 2,
    silver: 1,
    bronze: 0,
    total: 6,
    status: 'warning',
    updated: '2020-11-04T14:36:22.000Z',
    abbrevation: 'NC',
    switch: false,
    chkbox: false,
    colorpick: '#BF6397',
  },
  {
    athlete: 'Ryosuke Irie',
    age: 22,
    country: 'Japan',
    year: 2012,
    date: '2021-03-09T12:15:06.692Z',
    sport: 'Swimming',
    gold: 0,
    silver: 2,
    bronze: 1,
    total: 6,
    status: 'warning',
    updated: '2020-11-04T14:36:22.000Z',
    abbrevation: 'NC',
    switch: false,
    chkbox: false,
    colorpick: '#BF6397',
  },
  {
    athlete: 'Cullen Jones',
    age: 28,
    country: 'United States',
    year: 2012,
    date: '2021-03-09T12:15:06.692Z',
    sport: 'Swimming',
    gold: 1,
    silver: 2,
    bronze: 0,
    total: 6,
    status: 'warning',
    updated: '2020-11-04T14:36:22.000Z',
    abbrevation: 'NC',
    switch: false,
    chkbox: false,
    colorpick: '#BF6397',
  },
  {
    athlete: 'Ranomi Kromowidjojo',
    age: 21,
    country: 'Netherlands',
    year: 2012,
    date: '2021-03-09T12:15:06.692Z',
    sport: 'Swimming',
    gold: 2,
    silver: 1,
    bronze: 0,
    total: 6,
    status: 'warning',
    updated: '2020-11-04T14:36:22.000Z',
    abbrevation: 'NC',
    switch: false,
    chkbox: false,
    colorpick: '#BF6397',
  },
  {
    athlete: 'Camille Muffat',
    age: 22,
    country: 'France',
    year: 2012,
    date: '2021-03-09T12:15:06.692Z',
    sport: 'Swimming',
    gold: 1,
    silver: 1,
    bronze: 1,
    total: 6,
    status: 'warning',
    updated: '2020-11-04T14:36:22.000Z',
    abbrevation: 'NC',
    switch: false,
    chkbox: false,
    colorpick: '#BF6397',
  },
  {
    athlete: 'Mel Schlanger',
    age: 25,
    country: 'Australia',
    year: 2012,
    date: '2021-03-09T12:15:06.692Z',
    sport: 'Swimming',
    gold: 1,
    silver: 2,
    bronze: 0,
    total: 6,
    status: 'warning',
    updated: '2020-11-04T14:36:22.000Z',
    abbrevation: 'NC',
    switch: false,
    chkbox: false,
    colorpick: '#BF6397',
  },
  {
    athlete: 'Emily Seebohm',
    age: 20,
    country: 'Australia',
    year: 2012,
    date: '2021-03-09T12:15:06.692Z',
    sport: 'Swimming',
    gold: 1,
    silver: 2,
    bronze: 0,
    total: 6,
    status: 'major',
    updated: '2020-11-04T14:36:22.000Z',
    abbrevation: 'NC',
    switch: false,
    chkbox: false,
    colorpick: '#BF6397',
  },
  {
    athlete: 'Rebecca Soni',
    age: 25,
    country: 'United States',
    year: 2012,
    date: '2021-03-09T12:15:06.692Z',
    sport: 'Swimming',
    gold: 2,
    silver: 1,
    bronze: 0,
    total: 6,
    status: 'major',
    updated: '2020-11-04T14:36:22.000Z',
    abbrevation: 'NC',
    switch: false,
    chkbox: false,
    colorpick: '#BF6397',
  },
  {
    athlete: 'Satomi Suzuki',
    age: 21,
    country: 'Japan',
    year: 2012,
    date: '2021-03-09T12:15:06.692Z',
    sport: 'Swimming',
    gold: 0,
    silver: 1,
    bronze: 2,
    total: 6,
    status: 'major',
    updated: '2020-11-04T14:36:22.000Z',
    abbrevation: 'NC',
    switch: false,
    chkbox: false,
    colorpick: '#BF6397',
  },
  {
    athlete: 'Dana Vollmer',
    age: 24,
    country: 'United States',
    year: 2012,
    date: '2021-03-09T12:15:06.692Z',
    sport: 'Swimming',
    gold: 3,
    silver: 0,
    bronze: 0,
    total: 6,
    status: 'critical',
    updated: '2020-11-04T14:36:22.000Z',
    abbrevation: 'NC',
    switch: false,
    chkbox: false,
    colorpick: '#BF6397',
  },
  {
    athlete: 'Alain Bernard',
    age: 25,
    country: 'France',
    year: 2008,
    date: '2021-03-09T12:15:06.692Z',
    sport: 'Swimming',
    gold: 1,
    silver: 1,
    bronze: 1,
    total: 6,
    status: 'critical',
    updated: '2020-11-04T14:36:22.000Z',
    abbrevation: 'NC',
    switch: false,
    chkbox: false,
    colorpick: '#BF6397',
  },
  {
    athlete: 'László Cseh Jr.',
    age: 22,
    country: 'Hungary',
    year: 2008,
    date: '2021-03-09T12:15:06.692Z',
    sport: 'Swimming',
    gold: 0,
    silver: 3,
    bronze: 0,
    total: 6,
    status: 'critical',
    updated: '2020-11-04T14:36:22.000Z',
    abbrevation: 'NC',
    switch: false,
    chkbox: false,
    colorpick: '#BF6397',
  },
  {
    athlete: 'Matt Grevers',
    age: 23,
    country: 'United States',
    year: 2008,
    date: '2021-03-09T12:15:06.692Z',
    sport: 'Swimming',
    gold: 2,
    silver: 1,
    bronze: 0,
    total: 6,
    status: 'critical',
    updated: '2020-11-04T14:36:22.000Z',
    abbrevation: 'NC',
    switch: false,
    chkbox: false,
    colorpick: '#BF6397',
  },
  {
    athlete: 'Margaret Hoelzer',
    age: 25,
    country: 'United States',
    year: 2008,
    date: '2021-03-09T12:15:06.692Z',
    sport: 'Swimming',
    gold: 0,
    silver: 2,
    bronze: 1,
    total: 6,
    status: 'critical',
    updated: '2020-11-04T14:36:22.000Z',
    abbrevation: 'NC',
    switch: false,
    chkbox: false,
    colorpick: '#BF6397',
  },
  {
    athlete: 'Katie Hoff',
    age: 19,
    country: 'United States',
    year: 2008,
    date: '2021-03-09T12:15:06.692Z',
    sport: 'Swimming',
    gold: 0,
    silver: 1,
    bronze: 2,
    total: 6,
    status: 'critical',
    updated: '2020-11-04T14:36:22.000Z',
    abbrevation: 'NC',
    switch: false,
    chkbox: false,
    colorpick: '#BF6397',
  },
  {
    athlete: 'Leisel Jones',
    age: 22,
    country: 'Australia',
    year: 2008,
    date: '2021-03-09T12:15:06.692Z',
    sport: 'Swimming',
    gold: 2,
    silver: 1,
    bronze: 0,
    total: 6,
    status: 'critical',
    updated: '2020-11-04T14:36:22.000Z',
    abbrevation: 'NC',
    switch: false,
    chkbox: false,
    colorpick: '#BF6397',
  },
  {
    athlete: 'Kosuke Kitajima',
    age: 25,
    country: 'Japan',
    year: 2008,
    date: '2021-03-09T12:15:06.692Z',
    sport: 'Swimming',
    gold: 2,
    silver: 0,
    bronze: 1,
    total: 6,
    status: 'critical',
    updated: '2020-11-04T14:36:22.000Z',
    abbrevation: 'NC',
    switch: false,
    chkbox: false,
    colorpick: '#BF6397',
  },
  {
    athlete: 'Andrew Lauterstein',
    age: 21,
    country: 'Australia',
    year: 2008,
    date: '2021-03-09T12:15:06.692Z',
    sport: 'Swimming',
    gold: 0,
    silver: 1,
    bronze: 2,
    total: 6,
    status: 'critical',
    updated: '2020-11-04T14:36:22.000Z',
    abbrevation: 'NC',
    switch: false,
    chkbox: false,
    colorpick: '#BF6397',
  },
  {
    athlete: 'Jason Lezak',
    age: 32,
    country: 'United States',
    year: 2008,
    date: '2021-03-09T12:15:06.692Z',
    sport: 'Swimming',
    gold: 2,
    silver: 0,
    bronze: 1,
    total: 6,
    status: 'critical',
    updated: '2020-11-04T14:36:22.000Z',
    abbrevation: 'NC',
    switch: false,
    chkbox: false,
    colorpick: '#BF6397',
  },
  {
    athlete: 'Pang Jiaying',
    age: 23,
    country: 'China',
    year: 2008,
    date: '2021-03-09T12:15:06.692Z',
    sport: 'Swimming',
    gold: 0,
    silver: 1,
    bronze: 2,
    total: 6,
    status: 'critical',
    updated: '2020-11-04T14:36:22.000Z',
    abbrevation: 'NC',
    switch: false,
    chkbox: false,
    colorpick: '#BF6397',
  },
  {
    athlete: 'Aaron Peirsol',
    age: 25,
    country: 'United States',
    year: 2008,
    date: '2021-03-09T12:15:06.692Z',
    sport: 'Swimming',
    gold: 2,
    silver: 1,
    bronze: 0,
    total: 6,
    status: 'critical',
    updated: '2020-11-04T14:36:22.000Z',
    abbrevation: 'NC',
    switch: false,
    chkbox: false,
    colorpick: '#BF6397',
  },
  {
    athlete: 'Steph Rice',
    age: 20,
    country: 'Australia',
    year: 2008,
    date: '2021-03-09T12:15:06.692Z',
    sport: 'Swimming',
    gold: 3,
    silver: 0,
    bronze: 0,
    total: 6,
    status: 'critical',
    updated: '2020-11-04T14:36:22.000Z',
    abbrevation: 'NC',
    switch: false,
    chkbox: false,
    colorpick: '#BF6397',
  },
  {
    athlete: 'Jess Schipper',
    age: 21,
    country: 'Australia',
    year: 2008,
    date: '2021-03-09T12:15:06.692Z',
    sport: 'Swimming',
    gold: 1,
    silver: 0,
    bronze: 2,
    total: 6,
    status: 'critical',
    updated: '2020-11-04T14:36:22.000Z',
    abbrevation: 'NC',
    switch: false,
    chkbox: false,
    colorpick: '#BF6397',
  },
  {
    athlete: 'Rebecca Soni',
    age: 21,
    country: 'United States',
    year: 2008,
    date: '2021-03-09T12:15:06.692Z',
    sport: 'Swimming',
    gold: 1,
    silver: 2,
    bronze: 0,
    total: 6,
    status: 'critical',
    updated: '2020-11-04T14:36:22.000Z',
    abbrevation: 'NC',
    switch: false,
    chkbox: false,
    colorpick: '#BF6397',
  },
  {
    athlete: 'Eamon Sullivan',
    age: 22,
    country: 'Australia',
    year: 2008,
    date: '2021-03-09T12:15:06.692Z',
    sport: 'Swimming',
    gold: 0,
    silver: 2,
    bronze: 1,
    total: 6,
    status: 'critical',
    updated: '2020-11-04T14:36:22.000Z',
    abbrevation: 'NC',
    switch: false,
    chkbox: false,
    colorpick: '#BF6397',
  },
  {
    athlete: 'Dara Torres',
    age: 41,
    country: 'United States',
    year: 2008,
    date: '2021-03-09T12:15:06.692Z',
    sport: 'Swimming',
    gold: 0,
    silver: 3,
    bronze: 0,
    total: 6,
    status: 'critical',
    updated: '2020-11-04T14:36:22.000Z',
    abbrevation: 'NC',
    switch: false,
    chkbox: false,
    colorpick: '#BF6397',
  },
  {
    athlete: 'Amanda Beard',
    age: 22,
    country: 'United States',
    year: 2004,
    date: '29/08/2004',
    sport: 'Swimming',
    gold: 1,
    silver: 2,
    bronze: 0,
    total: 6,
    status: 'major',
    updated: '2020-11-04T14:36:22.000Z',
    abbrevation: 'NC',
    switch: false,
    chkbox: false,
    colorpick: '#BF6397',
  },
  {
    athlete: 'Antje Buschschulte',
    age: 25,
    country: 'Germany',
    year: 2004,
    date: '29/08/2004',
    sport: 'Swimming',
    gold: 0,
    silver: 0,
    bronze: 3,
    total: 6,
    status: 'major',
    updated: '2020-11-04T14:36:22.000Z',
    abbrevation: 'NC',
    switch: false,
    chkbox: false,
    colorpick: '#BF6397',
  },
  {
    athlete: 'Kirsty Coventry',
    age: 20,
    country: 'Zimbabwe',
    year: 2004,
    date: '29/08/2004',
    sport: 'Swimming',
    gold: 1,
    silver: 1,
    bronze: 1,
    total: 6,
    status: 'major',
    updated: '2020-11-04T14:36:22.000Z',
    abbrevation: 'NC',
    switch: false,
    chkbox: false,
    colorpick: '#BF6397',
  },
  {
    athlete: 'Ian Crocker',
    age: 21,
    country: 'United States',
    year: 2004,
    date: '29/08/2004',
    sport: 'Swimming',
    gold: 1,
    silver: 1,
    bronze: 1,
    total: 6,
    status: 'major',
    updated: '2020-11-04T14:36:22.000Z',
    abbrevation: 'NC',
    switch: false,
    chkbox: false,
    colorpick: '#BF6397',
  },
  {
    athlete: 'Grant Hackett',
    age: 24,
    country: 'Australia',
    year: 2004,
    date: '29/08/2004',
    sport: 'Swimming',
    gold: 1,
    silver: 2,
    bronze: 0,
    total: 6,
    status: 'major',
    updated: '2020-11-04T14:36:22.000Z',
    abbrevation: 'NC',
    switch: false,
    chkbox: false,
    colorpick: '#BF6397',
  },
  {
    athlete: 'Brendan Hansen',
    age: 22,
    country: 'United States',
    year: 2004,
    date: '29/08/2004',
    sport: 'Swimming',
    gold: 1,
    silver: 1,
    bronze: 1,
    total: 6,
    status: 'major',
    updated: '2020-11-04T14:36:22.000Z',
    abbrevation: 'NC',
    switch: false,
    chkbox: false,
    colorpick: '#BF6397',
  },
  {
    athlete: 'Jodie Henry',
    age: 20,
    country: 'Australia',
    year: 2004,
    date: '29/08/2004',
    sport: 'Swimming',
    gold: 3,
    silver: 0,
    bronze: 0,
    total: 6,
    status: 'major',
    updated: '2020-11-04T14:36:22.000Z',
    abbrevation: 'NC',
    switch: false,
    chkbox: false,
    colorpick: '#BF6397',
  },
  {
    athlete: 'Otylia Jedrzejczak',
    age: 20,
    country: 'Poland',
    year: 2004,
    date: '29/08/2004',
    sport: 'Swimming',
    gold: 1,
    silver: 2,
    bronze: 0,
    total: 6,
    status: 'major',
    updated: '2020-11-04T14:36:22.000Z',
    abbrevation: 'NC',
    switch: false,
    chkbox: false,
    colorpick: '#BF6397',
  },
  {
    athlete: 'Leisel Jones',
    age: 18,
    country: 'Australia',
    year: 2004,
    date: '29/08/2004',
    sport: 'Swimming',
    gold: 1,
    silver: 1,
    bronze: 1,
    total: 6,
    status: 'major',
    updated: '2020-11-04T14:36:22.000Z',
    abbrevation: 'NC',
    switch: false,
    chkbox: false,
    colorpick: '#BF6397',
  },
  {
    athlete: 'Kosuke Kitajima',
    age: 21,
    country: 'Japan',
    year: 2004,
    date: '29/08/2004',
    sport: 'Swimming',
    gold: 2,
    silver: 0,
    bronze: 1,
    total: 6,
    status: 'major',
    updated: '2020-11-04T14:36:22.000Z',
    abbrevation: 'NC',
    switch: false,
    chkbox: false,
    colorpick: '#BF6397',
  },
  {
    athlete: 'Laure Manaudou',
    age: 17,
    country: 'France',
    year: 2004,
    date: '29/08/2004',
    sport: 'Swimming',
    gold: 1,
    silver: 1,
    bronze: 1,
    total: 6,
    status: 'major',
    updated: '2020-11-04T14:36:22.000Z',
    abbrevation: 'NC',
    switch: false,
    chkbox: false,
    colorpick: '#BF6397',
  },
  {
    athlete: 'Aaron Peirsol',
    age: 21,
    country: 'United States',
    year: 2004,
    date: '29/08/2004',
    sport: 'Swimming',
    gold: 3,
    silver: 0,
    bronze: 0,
    total: 6,
    status: 'major',
    updated: '2020-11-04T14:36:22.000Z',
    abbrevation: 'NC',
    switch: false,
    chkbox: false,
    colorpick: '#BF6397',
  },
  {
    athlete: 'Kaitlin Sandeno',
    age: 21,
    country: 'United States',
    year: 2004,
    date: '29/08/2004',
    sport: 'Swimming',
    gold: 1,
    silver: 1,
    bronze: 1,
    total: 6,
    status: 'major',
    updated: '2020-11-04T14:36:22.000Z',
    abbrevation: 'NC',
    switch: false,
    chkbox: false,
    colorpick: '#BF6397',
  },
  {
    athlete: 'Roland Schoeman',
    age: 24,
    country: 'South Africa',
    year: 2004,
    date: '29/08/2004',
    sport: 'Swimming',
    gold: 1,
    silver: 1,
    bronze: 1,
    total: 6,
    status: 'major',
    updated: '2020-11-04T14:36:22.000Z',
    abbrevation: 'NC',
    switch: false,
    chkbox: false,
    colorpick: '#BF6397',
  },
  {
    athlete: 'Pieter van den Hoogenband',
    age: 26,
    country: 'Netherlands',
    year: 2004,
    date: '29/08/2004',
    sport: 'Swimming',
    gold: 1,
    silver: 2,
    bronze: 0,
    total: 6,
    status: 'major',
    updated: '2020-11-04T14:36:22.000Z',
    abbrevation: 'NC',
    switch: false,
    chkbox: false,
    colorpick: '#BF6397',
  },
  {
    athlete: 'Therese Alshammar',
    age: 23,
    country: 'Sweden',
    year: 2000,
    date: '01/10/2000',
    sport: 'Swimming',
    gold: 0,
    silver: 2,
    bronze: 1,
    total: 6,
    status: 'critical',
    updated: '2020-11-04T14:36:22.000Z',
    abbrevation: 'NC',
    switch: false,
    chkbox: false,
    colorpick: '#BF6397',
  },
  {
    athlete: 'Yana Klochkova',
    age: 18,
    country: 'Ukraine',
    year: 2000,
    date: '01/10/2000',
    sport: 'Swimming',
    gold: 2,
    silver: 1,
    bronze: 0,
    total: 6,
    status: 'critical',
    updated: '2020-11-04T14:36:22.000Z',
    abbrevation: 'NC',
    switch: false,
    chkbox: false,
    colorpick: '#BF6397',
  },
  {
    athlete: 'Lenny Krayzelburg',
    age: 24,
    country: 'United States',
    year: 2000,
    date: '01/10/2000',
    sport: 'Swimming',
    gold: 3,
    silver: 0,
    bronze: 0,
    total: 6,
    status: 'critical',
    updated: '2020-11-04T14:36:22.000Z',
    abbrevation: 'NC',
    switch: false,
    chkbox: false,
    colorpick: '#BF6397',
  },
  {
    athlete: 'Massimiliano Rosolino',
    age: 22,
    country: 'Italy',
    year: 2000,
    date: '01/10/2000',
    sport: 'Swimming',
    gold: 1,
    silver: 1,
    bronze: 1,
    total: 6,
    status: 'critical',
    updated: '2020-11-04T14:36:22.000Z',
    abbrevation: 'NC',
    switch: false,
    chkbox: false,
    colorpick: '#BF6397',
  },
  {
    athlete: 'Petria Thomas',
    age: 25,
    country: 'Australia',
    year: 2000,
    date: '01/10/2000',
    sport: 'Swimming',
    gold: 0,
    silver: 2,
    bronze: 1,
    total: 6,
    status: 'critical',
    updated: '2020-11-04T14:36:22.000Z',
    abbrevation: 'NC',
    switch: false,
    chkbox: false,
    colorpick: '#BF6397',
  },
  {
    athlete: 'Matt Welsh',
    age: 23,
    country: 'Australia',
    year: 2000,
    date: '01/10/2000',
    sport: 'Swimming',
    gold: 0,
    silver: 2,
    bronze: 1,
    total: 6,
    status: 'critical',
    updated: '2020-11-04T14:36:22.000Z',
    abbrevation: 'NC',
    switch: false,
    chkbox: false,
    colorpick: '#BF6397',
  },
  {
    athlete: 'Lee Jeong-Su',
    age: 20,
    country: 'South Korea',
    year: 2010,
    date: '28/02/2010',
    sport: 'Short-Track Speed Skating',
    gold: 2,
    silver: 1,
    bronze: 0,
    total: 6,
    status: 'critical',
    updated: '2020-11-04T14:36:22.000Z',
    abbrevation: 'NC',
    switch: false,
    chkbox: false,
    colorpick: '#BF6397',
  },
  {
    athlete: 'Apolo Anton Ohno',
    age: 27,
    country: 'United States',
    year: 2010,
    date: '28/02/2010',
    sport: 'Short-Track Speed Skating',
    gold: 0,
    silver: 1,
    bronze: 2,
    total: 6,
    status: 'critical',
    updated: '2020-11-04T14:36:22.000Z',
    abbrevation: 'NC',
    switch: false,
    chkbox: false,
    colorpick: '#BF6397',
  },
  {
    athlete: 'Wang Meng',
    age: 24,
    country: 'China',
    year: 2010,
    date: '28/02/2010',
    sport: 'Short-Track Speed Skating',
    gold: 3,
    silver: 0,
    bronze: 0,
    total: 6,
    status: 'critical',
    updated: '2020-11-04T14:36:22.000Z',
    abbrevation: 'NC',
    switch: false,
    chkbox: false,
    colorpick: '#BF6397',
  },
  {
    athlete: 'Jin Seon-Yu',
    age: 17,
    country: 'South Korea',
    year: 2006,
    date: '26/02/2006',
    sport: 'Short-Track Speed Skating',
    gold: 3,
    silver: 0,
    bronze: 0,
    total: 6,
    status: 'critical',
    updated: '2020-11-04T14:36:22.000Z',
    abbrevation: 'NC',
    switch: false,
    chkbox: false,
    colorpick: '#BF6397',
  },
  {
    athlete: 'Lee Ho-Seok',
    age: 19,
    country: 'South Korea',
    year: 2006,
    date: '26/02/2006',
    sport: 'Short-Track Speed Skating',
    gold: 1,
    silver: 2,
    bronze: 0,
    total: 6,
    status: 'critical',
    updated: '2020-11-04T14:36:22.000Z',
    abbrevation: 'NC',
    switch: false,
    chkbox: false,
    colorpick: '#BF6397',
  },
  {
    athlete: 'Apolo Anton Ohno',
    age: 23,
    country: 'United States',
    year: 2006,
    date: '26/02/2006',
    sport: 'Short-Track Speed Skating',
    gold: 1,
    silver: 0,
    bronze: 2,
    total: 6,
    status: 'critical',
    updated: '2020-11-04T14:36:22.000Z',
    abbrevation: 'NC',
    switch: false,
    chkbox: false,
    colorpick: '#BF6397',
  },
  {
    athlete: 'Wang Meng',
    age: 20,
    country: 'China',
    year: 2006,
    date: '26/02/2006',
    sport: 'Short-Track Speed Skating',
    gold: 1,
    silver: 1,
    bronze: 1,
    total: 6,
    status: 'critical',
    updated: '2020-11-04T14:36:22.000Z',
    abbrevation: 'NC',
    switch: false,
    chkbox: false,
    colorpick: '#BF6397',
  },
  {
    athlete: 'Marc Gagnon',
    age: 26,
    country: 'Canada',
    year: 2002,
    date: '24/02/2002',
    sport: 'Short-Track Speed Skating',
    gold: 2,
    silver: 0,
    bronze: 1,
    total: 6,
    status: 'critical',
    updated: '2020-11-04T14:36:22.000Z',
    abbrevation: 'NC',
    switch: false,
    chkbox: false,
    colorpick: '#BF6397',
  },
  {
    athlete: 'Yang Yang (A)',
    age: 25,
    country: 'China',
    year: 2002,
    date: '24/02/2002',
    sport: 'Short-Track Speed Skating',
    gold: 2,
    silver: 1,
    bronze: 0,
    total: 6,
    status: 'critical',
    updated: '2020-11-04T14:36:22.000Z',
    abbrevation: 'NC',
    switch: false,
    chkbox: false,
    colorpick: '#BF6397',
  },
  {
    athlete: 'Stephanie Beckert',
    age: 21,
    country: 'Germany',
    year: 2010,
    date: '28/02/2010',
    sport: 'Speed Skating',
    gold: 1,
    silver: 2,
    bronze: 0,
    total: 6,
    status: 'critical',
    updated: '2020-11-04T14:36:22.000Z',
    abbrevation: 'NC',
    switch: false,
    chkbox: false,
    colorpick: '#BF6397',
  },
  {
    athlete: 'Martina Sáblíková',
    age: 22,
    country: 'Czech Republic',
    year: 2010,
    date: '28/02/2010',
    sport: 'Speed Skating',
    gold: 2,
    silver: 0,
    bronze: 1,
    total: 6,
    status: 'critical',
    updated: '2020-11-04T14:36:22.000Z',
    abbrevation: 'NC',
    switch: false,
    chkbox: false,
    colorpick: '#BF6397',
  },
  {
    athlete: 'Enrico Fabris',
    age: 24,
    country: 'Italy',
    year: 2006,
    date: '26/02/2006',
    sport: 'Speed Skating',
    gold: 2,
    silver: 0,
    bronze: 1,
    total: 6,
    status: 'critical',
    updated: '2020-11-04T14:36:22.000Z',
    abbrevation: 'NC',
    switch: false,
    chkbox: false,
    colorpick: '#BF6397',
  },
  {
    athlete: 'Chad Hedrick',
    age: 28,
    country: 'United States',
    year: 2006,
    date: '26/02/2006',
    sport: 'Speed Skating',
    gold: 1,
    silver: 1,
    bronze: 1,
    total: 6,
    status: 'critical',
    updated: '2020-11-04T14:36:22.000Z',
    abbrevation: 'NC',
    switch: false,
    chkbox: false,
    colorpick: '#BF6397',
  },
  {
    athlete: 'Jochem Uytdehaage',
    age: 25,
    country: 'Netherlands',
    year: 2002,
    date: '24/02/2002',
    sport: 'Speed Skating',
    gold: 2,
    silver: 1,
    bronze: 0,
    total: 6,
    status: 'critical',
    updated: '2020-11-04T14:36:22.000Z',
    abbrevation: 'NC',
    switch: false,
    chkbox: false,
    colorpick: '#BF6397',
  },
  {
    athlete: 'Sabine Völker',
    age: 28,
    country: 'Germany',
    year: 2002,
    date: '24/02/2002',
    sport: 'Speed Skating',
    gold: 0,
    silver: 2,
    bronze: 1,
    total: 6,
    status: 'critical',
    updated: '2020-11-04T14:36:22.000Z',
    abbrevation: 'NC',
    switch: false,
    chkbox: false,
    colorpick: '#BF6397',
  },
  {
    athlete: 'Gregor Schlierenzauer',
    age: 20,
    country: 'Austria',
    year: 2010,
    date: '28/02/2010',
    sport: 'Ski Jumping',
    gold: 1,
    silver: 0,
    bronze: 2,
    total: 6,
    status: 'critical',
    updated: '2020-11-04T14:36:22.000Z',
    abbrevation: 'NC',
    switch: false,
    chkbox: false,
    colorpick: '#BF6397',
  },
  {
    athlete: 'Lars Bystøl',
    age: 27,
    country: 'Norway',
    year: 2006,
    date: '26/02/2006',
    sport: 'Ski Jumping',
    gold: 1,
    silver: 0,
    bronze: 2,
    total: 6,
    status: 'critical',
    updated: '2020-11-04T14:36:22.000Z',
    abbrevation: 'NC',
    switch: false,
    chkbox: false,
    colorpick: '#BF6397',
  },
  {
    athlete: 'Johnny Spillane',
    age: 29,
    country: 'United States',
    year: 2010,
    date: '28/02/2010',
    sport: 'Nordic Combined',
    gold: 0,
    silver: 3,
    bronze: 0,
    total: 6,
    status: 'critical',
    updated: '2020-11-04T14:36:22.000Z',
    abbrevation: 'NC',
    switch: false,
    chkbox: false,
    colorpick: '#BF6397',
  },
  {
    athlete: 'Felix Gottwald',
    age: 30,
    country: 'Austria',
    year: 2006,
    date: '26/02/2006',
    sport: 'Nordic Combined',
    gold: 2,
    silver: 1,
    bronze: 0,
    total: 6,
    status: 'critical',
    updated: '2020-11-04T14:36:22.000Z',
    abbrevation: 'NC',
    switch: false,
    chkbox: false,
    colorpick: '#BF6397',
  },
  {
    athlete: 'Georg Hettich',
    age: 27,
    country: 'Germany',
    year: 2006,
    date: '26/02/2006',
    sport: 'Nordic Combined',
    gold: 1,
    silver: 1,
    bronze: 1,
    total: 6,
    status: 'critical',
    updated: '2020-11-04T14:36:22.000Z',
    abbrevation: 'NC',
    switch: false,
    chkbox: false,
    colorpick: '#BF6397',
  },
  {
    athlete: 'Felix Gottwald',
    age: 26,
    country: 'Austria',
    year: 2002,
    date: '24/02/2002',
    sport: 'Nordic Combined',
    gold: 0,
    silver: 0,
    bronze: 3,
    total: 6,
    status: 'critical',
    updated: '2020-11-04T14:36:22.000Z',
    abbrevation: 'NC',
    switch: false,
    chkbox: false,
    colorpick: '#BF6397',
  },
  {
    athlete: 'Samppa Lajunen',
    age: 22,
    country: 'Finland',
    year: 2002,
    date: '24/02/2002',
    sport: 'Nordic Combined',
    gold: 3,
    silver: 0,
    bronze: 0,
    total: 6,
    status: 'critical',
    updated: '2020-11-04T14:36:22.000Z',
    abbrevation: 'NC',
    switch: false,
    chkbox: false,
    colorpick: '#BF6397',
  },
  {
    athlete: 'Aly Raisman',
    age: 18,
    country: 'United States',
    year: 2012,
    date: '2021-03-09T12:15:06.692Z',
    sport: 'Gymnastics',
    gold: 2,
    silver: 0,
    bronze: 1,
    total: 6,
    status: 'critical',
    updated: '2020-11-04T14:36:22.000Z',
    abbrevation: 'NC',
    switch: false,
    chkbox: false,
    colorpick: '#BF6397',
  },
  {
    athlete: 'Kohei Uchimura',
    age: 23,
    country: 'Japan',
    year: 2012,
    date: '2021-03-09T12:15:06.692Z',
    sport: 'Gymnastics',
    gold: 1,
    silver: 2,
    bronze: 0,
    total: 6,
    status: 'critical',
    updated: '2020-11-04T14:36:22.000Z',
    abbrevation: 'NC',
    switch: false,
    chkbox: false,
    colorpick: '#BF6397',
  },
  {
    athlete: 'Zou Kai',
    age: 24,
    country: 'China',
    year: 2012,
    date: '2021-03-09T12:15:06.692Z',
    sport: 'Gymnastics',
    gold: 2,
    silver: 0,
    bronze: 1,
    total: 6,
    status: 'critical',
    updated: '2020-11-04T14:36:22.000Z',
    abbrevation: 'NC',
    switch: false,
    chkbox: false,
    colorpick: '#BF6397',
  },
  {
    athlete: 'Cheng Fei',
    age: 20,
    country: 'China',
    year: 2008,
    date: '2021-03-09T12:15:06.692Z',
    sport: 'Gymnastics',
    gold: 1,
    silver: 0,
    bronze: 2,
    total: 6,
    status: 'critical',
    updated: '2020-11-04T14:36:22.000Z',
    abbrevation: 'NC',
    switch: false,
    chkbox: false,
    colorpick: '#BF6397',
  },
  {
    athlete: 'Yang Wei',
    age: 28,
    country: 'China',
    year: 2008,
    date: '2021-03-09T12:15:06.692Z',
    sport: 'Gymnastics',
    gold: 2,
    silver: 1,
    bronze: 0,
    total: 6,
    status: 'critical',
    updated: '2020-11-04T14:36:22.000Z',
    abbrevation: 'NC',
    switch: false,
    chkbox: false,
    colorpick: '#BF6397',
  },
];

export const COMMENTS_DATA = [
  {
    id: '1',
    author: 'Han Solo',
    comment: `We supply a series of design principles, practical patterns and high quality design resources (Sketch and Axure), to help people create their product prototypes beautifully and efficiently. We supply a series of design principles, practical patterns and high quality design resources (Sketch and Axure), to help people create their product prototypes beautifully and efficiently. We supply a series of design principles, practical patterns and high quality design resources (Sketch and Axure), to help people create their product prototypes beautifully and efficiently. We supply a series of design principles, practical patterns and high quality design resources (Sketch and Axure), to help people create their product prototypes beautifully and efficiently.`,
    dataTime: 1607360179616,
    switch: false,
    chkbox: false,
    colorpick: '#BF6397',
  },
  {
    id: '2',
    author: 'Han Solo',
    comment: `We supply a series of design principles, practical patterns and high quality design resources (Sketch and Axure), to help people create their product prototypes beautifully and efficiently.`,
    dataTime: 1607360179616,
    switch: false,
    chkbox: false,
    colorpick: '#BF6397',
  },
  {
    id: '3',
    author: 'Han Solo',
    comment: `We supply a series of design principles, practical patterns and high quality design resources (Sketch and Axure), to help people create their product prototypes beautifully and efficiently. We supply a series of design principles, practical patterns and high quality design resources (Sketch and Axure), to help people create their product prototypes beautifully and efficiently. We supply a series of design principles, practical patterns and high quality design resources (Sketch and Axure), to help people create their product prototypes beautifully and efficiently. We supply a series of design principles, practical patterns and high quality design resources (Sketch and Axure), to help people create their product prototypes beautifully and efficiently.`,
    dataTime: 1607360179616,
    switch: false,
    chkbox: false,
    colorpick: '#BF6397',
  },
  {
    id: '4',
    author: 'Han Solo',
    comment: `We supply a series of design principles, practical patterns and high quality design resources (Sketch and Axure), to help people create their product prototypes beautifully and efficiently.`,
    dataTime: 1607360179616,
    switch: false,
    chkbox: false,
    colorpick: '#BF6397',
  },
  {
    id: '5',
    author: 'Han Solo',
    comment: `We supply a series of design principles, practical patterns and high quality design resources (Sketch and Axure), to help people create their product prototypes beautifully and efficiently. We supply a series of design principles, practical patterns and high quality design resources (Sketch and Axure), to help people create their product prototypes beautifully and efficiently. We supply a series of design principles, practical patterns and high quality design resources (Sketch and Axure), to help people create their product prototypes beautifully and efficiently. We supply a series of design principles, practical patterns and high quality design resources (Sketch and Axure), to help people create their product prototypes beautifully and efficiently.`,
    dataTime: 1607360179616,
    switch: false,
    chkbox: false,
    colorpick: '#BF6397',
  },
  {
    id: '6',
    author: 'Han Solo',
    comment: `We supply a series of design principles, practical patterns and high quality design resources (Sketch and Axure), to help people create their product prototypes beautifully and efficiently.`,
    dataTime: 1607360179616,
    switch: false,
    chkbox: false,
    colorpick: '#BF6397',
  },
  {
    id: '7',
    author: 'Han Solo',
    comment: `We supply a series of design principles, practical patterns and high quality design resources (Sketch and Axure), to help people create their product prototypes beautifully and efficiently. We supply a series of design principles, practical patterns and high quality design resources (Sketch and Axure), to help people create their product prototypes beautifully and efficiently. We supply a series of design principles, practical patterns and high quality design resources (Sketch and Axure), to help people create their product prototypes beautifully and efficiently. We supply a series of design principles, practical patterns and high quality design resources (Sketch and Axure), to help people create their product prototypes beautifully and efficiently.`,
    dataTime: 1607360179616,
    switch: false,
    chkbox: false,
    colorpick: '#BF6397',
  },
  {
    id: '8',
    author: 'Han Solo',
    comment: `We supply a series of design principles, practical patterns and high quality design resources (Sketch and Axure), to help people create their product prototypes beautifully and efficiently.`,
    dataTime: 1607360179616,
    switch: false,
    chkbox: false,
    colorpick: '#BF6397',
  },
  {
    id: '9',
    author: 'Han Solo',
    comment: `We supply a series of design principles, practical patterns and high quality design resources (Sketch and Axure), to help people create their product prototypes beautifully and efficiently. We supply a series of design principles, practical patterns and high quality design resources (Sketch and Axure), to help people create their product prototypes beautifully and efficiently. We supply a series of design principles, practical patterns and high quality design resources (Sketch and Axure), to help people create their product prototypes beautifully and efficiently. We supply a series of design principles, practical patterns and high quality design resources (Sketch and Axure), to help people create their product prototypes beautifully and efficiently.`,
    dataTime: 1607360179616,
    switch: false,
    chkbox: false,
    colorpick: '#BF6397',
  },
  {
    id: '10',
    author: 'Han Solo',
    comment: `We supply a series of design principles, practical patterns and high quality design resources (Sketch and Axure), to help people create their product prototypes beautifully and efficiently.`,
    dataTime: 1607360179616,
    switch: false,
    chkbox: false,
    colorpick: '#BF6397',
  },
  {
    id: '11',
    author: 'Han Solo',
    comment: `We supply a series of design principles, practical patterns and high quality design resources (Sketch and Axure), to help people create their product prototypes beautifully and efficiently. We supply a series of design principles, practical patterns and high quality design resources (Sketch and Axure), to help people create their product prototypes beautifully and efficiently. We supply a series of design principles, practical patterns and high quality design resources (Sketch and Axure), to help people create their product prototypes beautifully and efficiently. We supply a series of design principles, practical patterns and high quality design resources (Sketch and Axure), to help people create their product prototypes beautifully and efficiently.`,
    dataTime: 1607360179616,
    switch: false,
    chkbox: false,
    colorpick: '#BF6397',
  },
  {
    id: '12',
    author: 'Han Solo',
    comment: `We supply a series of design principles, practical patterns and high quality design resources (Sketch and Axure), to help people create their product prototypes beautifully and efficiently.`,
    dataTime: 1607360179616,
    switch: false,
    chkbox: false,
    colorpick: '#BF6397',
  },
  {
    id: '13',
    author: 'Han Solo',
    comment: `We supply a series of design principles, practical patterns and high quality design resources (Sketch and Axure), to help people create their product prototypes beautifully and efficiently. We supply a series of design principles, practical patterns and high quality design resources (Sketch and Axure), to help people create their product prototypes beautifully and efficiently. We supply a series of design principles, practical patterns and high quality design resources (Sketch and Axure), to help people create their product prototypes beautifully and efficiently. We supply a series of design principles, practical patterns and high quality design resources (Sketch and Axure), to help people create their product prototypes beautifully and efficiently.`,
    dataTime: 1607360179616,
    switch: false,
    chkbox: false,
    colorpick: '#BF6397',
  },
  {
    id: '14',
    author: 'Han Solo',
    comment: `We supply a series of design principles, practical patterns and high quality design resources (Sketch and Axure), to help people create their product prototypes beautifully and efficiently.`,
    dataTime: 1607360179616,
    switch: false,
    chkbox: false,
    colorpick: '#BF6397',
  },
  {
    id: '15',
    author: 'Han Solo',
    comment: `We supply a series of design principles, practical patterns and high quality design resources (Sketch and Axure), to help people create their product prototypes beautifully and efficiently. We supply a series of design principles, practical patterns and high quality design resources (Sketch and Axure), to help people create their product prototypes beautifully and efficiently. We supply a series of design principles, practical patterns and high quality design resources (Sketch and Axure), to help people create their product prototypes beautifully and efficiently. We supply a series of design principles, practical patterns and high quality design resources (Sketch and Axure), to help people create their product prototypes beautifully and efficiently.`,
    dataTime: 1607360179616,
    switch: false,
    chkbox: false,
    colorpick: '#BF6397',
  },
  {
    id: '16',
    author: 'Han Solo',
    comment: `We supply a series of design principles, practical patterns and high quality design resources (Sketch and Axure), to help people create their product prototypes beautifully and efficiently.`,
    dataTime: 1607360179616,
    switch: false,
    chkbox: false,
    colorpick: '#BF6397',
  },
  {
    id: '17',
    author: 'Han Solo',
    comment: `We supply a series of design principles, practical patterns and high quality design resources (Sketch and Axure), to help people create their product prototypes beautifully and efficiently. We supply a series of design principles, practical patterns and high quality design resources (Sketch and Axure), to help people create their product prototypes beautifully and efficiently. We supply a series of design principles, practical patterns and high quality design resources (Sketch and Axure), to help people create their product prototypes beautifully and efficiently. We supply a series of design principles, practical patterns and high quality design resources (Sketch and Axure), to help people create their product prototypes beautifully and efficiently.`,
    dataTime: 1607360179616,
    switch: false,
    chkbox: false,
    colorpick: '#BF6397',
  },
  {
    id: '18',
    author: 'Han Solo',
    comment: `We supply a series of design principles, practical patterns and high quality design resources (Sketch and Axure), to help people create their product prototypes beautifully and efficiently.`,
    dataTime: 1607360179616,
    switch: false,
    chkbox: false,
    colorpick: '#BF6397',
  },
];
